project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "slides/"
# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

lang: es

website:
  title: "Introducción a REDCap para Investigación Clínica"
  favicon: logo.png
  image: logo.png
  twitter-card: true
  site-url: https://ietsi-pfc2023-redcap.netlify.app/
  open-graph: true
  repo-url: https://github.com/psotob91/redcap-curso-ietsi2023
  repo-actions: [edit, issue]
  page-navigation: true
  reader-mode: true

  navbar:
    pinned: true
    background: "#0469BC"
    logo: logo.png
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Materiales"
        file: content/index.qmd
      - text: "REDCap de IETSI"
        href: "https://redcap-ietsi.essalud.gob.pe/redcap/"
      - icon: cloud-fill
        href: "https://drive.google.com/drive/folders/1aYzZRs7Y-XfulanYtD_O_J8dCMigwAIu?usp=share_link"
        aria-label: RStudio.cloud

  sidebar:
    - title: "Información general"
      style: "docked"
      search: true
      background: dark
      contents:
        - section: "Información general"
          contents:
            - content/index.qmd
        - section: "Materiales del curso"
          contents:
            - text: "Sesión 00"
              file: content/00-content.qmd
            - text: "Sesión 01"
              file: content/01-content.qmd
            - text: "Sesión 02"
              file: content/02-content.qmd
            - text: "Sesión 03"
              file: content/03-content.qmd
            - text: "Sesión 04"
              file: content/04-content.qmd
            - text: "Sesión 05"
              file: content/05-content.qmd
            - text: "Sesión 06"
              file: content/06-content.qmd
            - text: "Sesión 07"
              file: content/07-content.qmd
            - text: "Sesión 08"
              file: content/08-content.qmd
            - text: "Sesión 09"
              file: content/09-content.qmd
            - text: "Sesión 10"
              file: content/10-content.qmd
            - text: "Sesión 11"
              file: content/11-content.qmd
            - text: "Sesión 12"
              file: content/12-content.qmd

  page-footer:
    left: |
      Contenido {{< fa brands creative-commons >}} {{< var course.copyright_year >}} por [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) para el [{{< var school.name >}}]({{< var school.url >}}) <br>
      Todo el contenido está bajo {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Hecho con {{< fa brands r-project >}} y [Quarto](https://quarto.org/)<br>
      [Ver el código fuente en {{< fa brands github >}} GitHub]({{< var course.github >}})
    border: true
    background: light

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true

