---
title: "Sesión 01"
date: "2023-03-03"
---

## Objetivos

En esta sesión se buscará abordar los siguientes temas: 

-
-
-


## Materiales

::: {.panel-tabset}

### Clase grabada


<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/804768381?h=1ed32f4c93&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 1 - Introducci&amp;oacute;n a REDCap y Configuraci&amp;oacute;n General"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>

### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
slide_buttons("sesion01")
```

```{=html}
<iframe width="780" height="500" src="sesion01.html" title="Sesión 1 - Intro a R"></iframe>
```

### Talleres

- Puede descargar los archivos generados en la carpeta `taller01` en el siguiente enlace: [Aquí]().


:::


