---
title: "Sesión 07"
date: "2023-03-10"
---

## Objetivos

En esta sesión se buscará abordar los siguientes temas: 

- Grupo de Acceso a datos
- Calendarios
- Notificaciones 
- Automatización en REDCap


## Materiales

::: {.panel-tabset}

### Clase grabada

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/808547574?h=12d13c2939&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 7 - Configuraciones adicionales: Grupo de Acceso a Datos, Calendarios, y Notificaciones Automatizadas"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>


### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things-pdf.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
slide_buttons_pdf("/slides/sesion07")
```

```{=html}
<iframe width="780" height="500" src="../slides/sesion07.pdf" title="Sesión 7 - Configuraciones adicionales: Grupo de Acceso a Datos, Calendarios, y Notificaciones Automatizadas"></iframe>
```

:::


