---
title: "Sesión 09"
date: "2023-03-17"
---

## Objetivos

En esta sesión se buscará abordar los siguientes temas: 

- Módulo de Calidad de Datos
- Validación de datos
- Validación antes de recolectar datos
- Validación interna
- Validación externa


## Materiales

::: {.panel-tabset}

### Clase grabada

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/810627823?h=e2d89d1e5b&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Sesi&amp;oacute;n 9 - Uso de herramientas de aseguramiento y control de calidad de datos"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>


### Slides

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
```

```{r show-slide-tabs1, echo=FALSE, results="asis"}
slide_buttons("/slides/sesion09")
```

```{=html}
<iframe width="780" height="500" src="../slides/sesion09.html" title="Sesión 9 - Uso de herramientas de aseguramiento y control de calidad de datos"></iframe>
```


:::


