---
title: "Sesión 12"
date: "2023-03-17"
---

:::{.callout-important collapse=false appearance='default' icon=true}
## Acerca de esta sesión

Por limitaciones de tiempo no se pudó realizar esta sesión de manera sincrónica. En su remplazo, hemos colgado una serie de videos relativametne cortos que abordan los tópicos que hubiéramos deseado compartirles en clase. ¡Vaya que el curso nos quedó corto! Esperamos que hayan disfrutado del curso y les sea de mucho provecho en sus proyectos venideros.

:::


## Objetivos

En esta sesión se buscará abordar los siguientes temas: 

- Aleatorización en REDCap
- Doble entrada de datos
- Reportes en REDCap
- Módulos externos
- Clonar instrumentos en REDCap
- Dashboards en REDCap
- Action tags
- Campos calculados
- Transferencia de segmentos de datos (piping)
- SQL Dinámico en REDCap
- Tareas cron
- Plugins / hooks
- Conferencias Mundiales de REDCap


## Misceláneas básicas

::: {.panel-tabset}

### Aleatorización

<iframe width="983" height="553" src="https://www.youtube.com/embed/MhnxiEKYwNE" title="Aleatorizacion" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### Doble entrada de datos

<iframe width="983" height="553" src="https://www.youtube.com/embed/PN2KyQ3lSlY" title="REDCap Advanced Tutorial: Double Data Entry" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### Reportes en REDCap

<iframe width="1048" height="478" src="https://www.youtube.com/embed/d9eYNZ7t1N0" title="REDCap Series ¿Cómo se hace? - Reportes" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### Módulos externos

<iframe width="983" height="553" src="https://www.youtube.com/embed/WLBqxHMDQxY" title="REDCap Series ¿Cómo se hace? - Modulos externos" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### Clonar instrumentos en REDCap

<iframe width="983" height="553" src="https://www.youtube.com/embed/WLBqxHMDQxY" title="REDCap Series ¿Cómo se hace? - Modulos externos" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

:::


## Misceláneas intermedias

::: {.panel-tabset}


### Dashboards en REDCap

<iframe width="1041" height="553" src="https://www.youtube.com/embed/sT_9To5NlSQ" title="IU REDCap: Project Dashboards" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### Action tags

<iframe width="1021" height="553" src="https://www.youtube.com/embed/7h5263ta7fM" title="Action Tags" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### Campos calculados

<iframe width="983" height="553" src="https://www.youtube.com/embed/QtEc_EkVtSw" title="Campos calculados" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### Transferencia de segmentos de datos (piping)

<iframe width="983" height="553" src="https://www.youtube.com/embed/I_zBSBcdtRc" title="Usos creativos del Piping" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

:::

## Misceláneas avanzadas

::: {.panel-tabset}

### SQL Dinámico en REDCap

<iframe width="983" height="553" src="https://www.youtube.com/embed/zjTqMoXLizI" title="SQL Dinamico" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### Tareas cron

<iframe width="983" height="553" src="https://www.youtube.com/embed/Tm6w3l2onKI" title="Tarea Cron" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### Plugins / hooks

<iframe width="885" height="553" src="https://www.youtube.com/embed/zBKxFFiheQc" title="Plugins/hooks" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

:::

## Conferencias Mundiales de REDCap

::: {.panel-tabset}

### REDCap Con Hispano 2021

<iframe width="983" height="553" src="https://www.youtube.com/embed/BLg-sF5NLlE?list=PLUOKfjU7M9weNceHLRjNdDUDF_uvGbCqN" title="¿Por qué REDCap?" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

### REDCap Con Hispano 2022

<iframe width="983" height="553" src="https://www.youtube.com/embed/jp6Hio_XKC4?list=PLUOKfjU7M9wcOpTUnOnVZc2vFJAYGznJ9" title="Mayo 19 - ¿Qué y Por qué REDCap?" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

:::